swagger: "2.0"
info:
  version: "1.0.0"
  title: Internal Environment Manager API
host: environmentmanager.corp.local
basePath: /em
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /initial-data:
    x-swagger-router-controller: initial-data-controller
    get:
      operationId: getInitialData
      summary: Used for the purposes of login to the Environment Manager application.
      tags:
        - Login
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
      responses:
        200:
          description: JSONP with initial state of the application.
