AWSTemplateFormatVersion: '2010-09-09'
Description: Environment Manager Dynamo Near Capacity Alerts
Parameters:
  DynamoCapacityWarningsSNSTopicArn:
    Type: String
    Description: Something nice and descriptive. 
Resources:
  LambdaFailureAlert:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      # Should actions be executed when there is a change in the alarms state
      ActionsEnabled: true
      # SNS topic on which to publish the alarm
      AlarmActions: 
        - !Ref DynamoCapacityWarningsSNSTopicArn
      AlarmDescription: Reports when a DynamoDB table is near capacity.
      AlarmName: EnvironmentManagerLambdaErrorNotification
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: ConsumedReadCapacityUnits
      Namespace: 'AWS/DynamoDB'
      # Multiple of 60, measured in seconds
      Period: 60
      Statistic: Sum
      Threshold: 0