version: 0.0
os: linux
files:
  - source: /
    destination: /opt/environment-manager
hooks:
  ApplicationStop:
    - location: deployment/code-deploy/application-stop.sh
      runas: root
  BeforeInstall:
    - location: deployment/code-deploy/before-install.sh
      runas: root
  AfterInstall:
    - location: deployment/code-deploy/on-after-install.sh
      runas: root
  ApplicationStart:
    - location: deployment/code-deploy/application-start.sh
      runas: root
  ValidateService:
    - location: deployment/code-deploy/validate-service.sh
      runas: root
