AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  EnvironmentManagerChangeEvent:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      Policies: AmazonSNSFullAccess
      CodeUri: s3://sns-test-bucket-testing/EnvironmentManagerEvents.zip
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: /events/
            Method: put
  EMConfigurationChange: 
    Type: "AWS::SNS::Topic"
    Properties: 
      TopicName: "EMConfigurationChange"
  EMOperationsChange:
    Type: "AWS::SNS::Topic"
    Properties: 
      TopicName: "EMOperationsChange"
