AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Publication of Environment Manager Change Events
Resources:
  EnvironmentManagerCongfigurationChange:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.configurationChange
      Runtime: nodejs4.3
      CodeUri: file
      Policies: AmazonDynamoDBReadOnlyAccess
      # Environment:
      #   Variables:
      #     TABLE_NAME: !Ref Table
      Events:
        PutResourcee :
          Type: Api
          Properties:
            Path: /events/configuration
            Method: put
  EnvironmentManagerOperationsChange:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.operationsChange
      Runtime: nodejs4.3
      # CodeUri: s3://bucketName/codepackage.zip
      Policies: AmazonDynamoDBFullAccess
      # Environment:
      #   Variables:
      #     TABLE_NAME: !Ref Table
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: /events/operations
            Method: put
  # Table:
  #   Type: AWS::Serverless::SimpleTable