AWSTemplateFormatVersion: '2010-09-09'
Description: Environment Manager Events
Resources:
  EnvironmentManagerConfigurationChangeAuditLambda:
    Properties:
      Code:
        S3Bucket: cloudformation-eu-west-1-743871665500
        S3Key: EnvironmentManagerConfigurationChangeAudit.zip
      Description: Lambda to record Configuration Change events.
      FunctionName: EnvironmentManagerConfigurationChangeAuditSubscription
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - EnvironmentManagerEventsAdminRole
        - Arn
      Runtime: nodejs4.3
    Type: AWS::Lambda::Function
  EnvironmentManagerConfigurationChangeAuditLambdaSubscription:
    Properties:
      Endpoint:
        Fn::GetAtt:
        - EnvironmentManagerConfigurationChangeAuditLambda
        - Arn
      Protocol: lambda
      TopicArn:
        Ref: EnvironmentManagerConfigurationChangeEventTopic
    Type: AWS::SNS::Subscription
  EnvironmentManagerConfigurationChangeEventTopic:
    Properties:
      DisplayName: EnvironmentManagerConfigurationChangeEventTopic
      TopicName: EnvironmentManagerConfigurationChange
    Type: AWS::SNS::Topic
  EnvironmentManagerEventsAdminRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            Effect: Allow
            Resource:
            - arn:aws:logs:*:*:*
          Version: '2012-10-17'
        PolicyName: EnvironmentManagerEventsCloudWatchPolicy
    Type: AWS::IAM::Role
  EnvironmentManagerEventsLambdaOperationsInvokePermission: 
    Type: 'AWS::Lambda::Permission'
    Properties: 
      Action: 'lambda:InvokeFunction'
      Principal: 'sns.amazonaws.com'
      SourceArn: !Ref EnvironmentManagerOperationsChangeEventTopic
      FunctionName: 
        Fn::GetAtt:
        - EnvironmentManagerOperationsChangeAuditLambda
        - Arn 
  EnvironmentManagerEventsLambdaConfigurationInvokePermission: 
    Type: 'AWS::Lambda::Permission'
    Properties: 
      Action: 'lambda:InvokeFunction'
      Principal: 'sns.amazonaws.com'
      SourceArn: !Ref EnvironmentManagerConfigurationChangeEventTopic
      FunctionName: 
        Fn::GetAtt:
        - EnvironmentManagerConfigurationChangeAuditLambda
        - Arn
  EnvironmentManagerOperationsChangeAuditLambda:
    Properties:
      Code:
        S3Bucket: cloudformation-eu-west-1-743871665500
        S3Key: EnvironmentManagerOperationsChangeAudit.zip
      Description: Lambda to record Operations Change events.
      FunctionName: EnvironmentManagerOperationsChangeAuditSubscription
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - EnvironmentManagerEventsAdminRole
        - Arn
      Runtime: nodejs4.3
    Type: AWS::Lambda::Function
  EnvironmentManagerOperationsChangeAuditLambdaSubscription:
    Properties:
      Endpoint:
        Fn::GetAtt:
        - EnvironmentManagerOperationsChangeAuditLambda
        - Arn
      Protocol: lambda
      TopicArn:
        Ref: EnvironmentManagerOperationsChangeEventTopic
    Type: AWS::SNS::Subscription
  EnvironmentManagerOperationsChangeEventTopic:
    Properties:
      DisplayName: EnvironmentManagerOperationsChangeEventTopic
      TopicName: EnvironmentManagerOperationsChange
    Type: AWS::SNS::Topic
