AWSTemplateFormatVersion: '2010-09-09'
Description: Environment Manager Events
Resources:
  #Section: Topics
  #Item: Configuration Change
  # This topic is a base path checked by SNS publish within EM. 
  # If the base path of an attempted publish to a topic doesn't contain this, it will not be allowed.
  InfraConfigurationChangeTopic:
    Properties:
      DisplayName: InfraConfigurationChange
      TopicName: InfraEnvironmentManagerConfigurationChange
    Type: AWS::SNS::Topic
  #Item: Operations Change
  # This topic is a base path checked by SNS publish within EM. 
  # If the base path of an attempted publish to a topic doesn't contain this, it will not be allowed.
  InfraOperationsChangeTopic:
    Properties:
      DisplayName: InfraOperationsChange
      TopicName: InfraEnvironmentManagerOperationsChange
    Type: AWS::SNS::Topic
  #Roles
  # Allow SNS subscribers/lambdas to write to Cloud Watch.
  InfraEnvironmentManagerEventsAdminRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            Effect: Allow
            Resource:
              - arn:aws:logs:*:*:*
          Version: '2012-10-17'
        PolicyName: InfraEnvironmentManagerEventsCloudWatchPolicy
    Type: AWS::IAM::Role
# To allow lambdas to subscribe to the topic, we need to know the ARN's they have been created with. 
# For the moment, this requires outputs being recorded from here and used in future stacks. 
# There is a _need_ to make this nicer!
Outputs:
  InfraConfigurationChangeTopicARN:
    Description: Configuration Change Topic ARN
    Value: !Ref InfraConfigurationChangeTopic
  InfraOperationsChangeTopicARN: 
    Description: Operations Change Topic ARN
    Value: !Ref InfraOperationsChangeTopic
  InfraEnvironmentManagerEventsAdminRoleARN:
    Description: Environment Manager Events Admin Role ARN.
    Value: 
      Fn::GetAtt:
      - InfraEnvironmentManagerEventsAdminRole
      - Arn
