AWSTemplateFormatVersion: '2010-09-09'
Description: Environment Manager Events
Resources:
  #Section: Topics
  #Item: Configuration Change
  ConfigurationChangeTopic:
    Properties:
      DisplayName: ConfigurationChange
      TopicName: EnvironmentManagerConfigurationChange
    Type: AWS::SNS::Topic
  #Item: Operations Change
  OperationsChangeTopic:
    Properties:
      DisplayName: OperationsChange
      TopicName: EnvironmentManagerOperationsChange
    Type: AWS::SNS::Topic
  #Roles
  EnvironmentManagerEventsAdminRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            Effect: Allow
            Resource:
              - arn:aws:logs:*:*:*
          Version: '2012-10-17'
        PolicyName: EnvironmentManagerEventsCloudWatchPolicy
    Type: AWS::IAM::Role
Outputs:
  ConfigurationChangeTopicARN:
    Description: Configuration Change Topic ARN
    Value: !Ref ConfigurationChangeTopic
  OperationsChangeTopicARN: 
    Description: Operations Change Topic ARN
    Value: !Ref OperationsChangeTopic
  EnvironmentManagerEventsAdminRoleARN:
    Description: Environment Manager Events Admin Role ARN.
    Value: 
      Fn::GetAtt:
      - EnvironmentManagerEventsAdminRole
      - Arn
