AWSTemplateFormatVersion: '2010-09-09'
Description: Environment Manager Events
Parameters: 
  EnvironmentManagerEventsAdminRole:
    Type: String
    Description: Admin role ARN given to the Environment Manager events stack.
  ConfigurationChangeEventTopic:
    Type: String
    Description: Configuration Change Event Topic ARN.
  OperationsChangeEventTopic:
    Type: String
    Description: Operations Change Event Topic ARN.
Resources:
  #Item: Configuration Change
  ConfigurationChangeAuditLambda:
    Properties:
      Code:
        S3Bucket: cloudformation-eu-west-1-743871665500
        S3Key: EnvironmentManagerConfigurationChangeAudit.zip
      Description: Lambda to record Configuration Change events.
      FunctionName: ConfigurationChangeAuditLambdaSubscription
      Handler: index.handler
      Role: !Ref EnvironmentManagerEventsAdminRole
      Runtime: nodejs4.3
    Type: AWS::Lambda::Function
  ConfigurationChangeAuditLambdaSubscription:
    Properties:
      Endpoint:
        Fn::GetAtt:
        - ConfigurationChangeAuditLambda
        - Arn
      Protocol: lambda
      TopicArn:
        Ref: ConfigurationChangeEventTopic
    Type: AWS::SNS::Subscription
  ConfigurationChangeAuditLambdaInvokePermission: 
    Type: 'AWS::Lambda::Permission'
    Properties: 
      Action: 'lambda:InvokeFunction'
      Principal: 'sns.amazonaws.com'
      SourceArn: !Ref ConfigurationChangeEventTopic
      FunctionName: 
        Fn::GetAtt:
        - ConfigurationChangeAuditLambda
        - Arn
  #Item: Operations Change
  OperationsChangeAuditLambda:
    Properties:
      Code:
        S3Bucket: cloudformation-eu-west-1-743871665500
        S3Key: EnvironmentManagerOperationsChangeAudit.zip
      Description: Lambda to record Operations Change events.
      FunctionName: OperationsChangeAuditLambdaSubscription
      Handler: index.handler
      Role: !Ref EnvironmentManagerEventsAdminRole
      Runtime: nodejs4.3
    Type: AWS::Lambda::Function
  OperationsChangeAuditLambdaSubscription:
    Properties:
      Endpoint:
        Fn::GetAtt:
        - OperationsChangeAuditLambda
        - Arn
      Protocol: lambda
      TopicArn: !Ref OperationsChangeEventTopic
    Type: AWS::SNS::Subscription
  OperationsChangeAuditLambdaInvokePermission: 
    Type: 'AWS::Lambda::Permission'
    Properties: 
      Action: 'lambda:InvokeFunction'
      Principal: 'sns.amazonaws.com'
      SourceArn: !Ref OperationsChangeEventTopic
      FunctionName: 
        Fn::GetAtt:
        - OperationsChangeAuditLambda
        - Arn
