AWSTemplateFormatVersion: '2010-09-09'
Description: Environment Manager Events
Parameters: 
  InfraEnvironmentManagerEventsAdminRole:
    Type: String
    Description: Admin role ARN given to the Environment Manager events stack.
  InfraConfigurationChangeEventTopic:
    Type: String
    Description: Configuration Change Event Topic ARN.
  InfraOperationsChangeEventTopic:
    Type: String
    Description: Operations Change Event Topic ARN.
Resources:
  #Item: Configuration Change
  InfraConfigurationChangeAuditLambda:
    Properties:
      Code:
        S3Bucket: cloudformation-eu-west-1-743871665500
        S3Key: EnvironmentManagerConfigurationChangeAudit.zip
      Description: Lambda to record Configuration Change events.
      FunctionName: InfraConfigurationChangeAuditLambdaSubscription
      Handler: index.handler
      Role: !Ref InfraEnvironmentManagerEventsAdminRole
      Runtime: nodejs4.3
    Type: AWS::Lambda::Function
  InfraConfigurationChangeAuditLambdaSubscription:
    Properties:
      Endpoint:
        Fn::GetAtt:
        - InfraConfigurationChangeAuditLambda
        - Arn
      Protocol: lambda
      TopicArn:
        Ref: InfraConfigurationChangeEventTopic
    Type: AWS::SNS::Subscription
  InfraConfigurationChangeAuditLambdaInvokePermission: 
    Type: 'AWS::Lambda::Permission'
    Properties: 
      Action: 'lambda:InvokeFunction'
      Principal: 'sns.amazonaws.com'
      SourceArn: !Ref InfraConfigurationChangeEventTopic
      FunctionName: 
        Fn::GetAtt:
        - InfraConfigurationChangeAuditLambda
        - Arn
  #Item: Operations Change
  InfraOperationsChangeAuditLambda:
    Properties:
      Code:
        S3Bucket: cloudformation-eu-west-1-743871665500
        S3Key: EnvironmentManagerOperationsChangeAudit.zip
      Description: Lambda to record Operations Change events.
      FunctionName: InfraOperationsChangeAuditLambdaSubscription
      Handler: index.handler
      Role: !Ref InfraEnvironmentManagerEventsAdminRole
      Runtime: nodejs4.3
    Type: AWS::Lambda::Function
  InfraOperationsChangeAuditLambdaSubscription:
    Properties:
      Endpoint:
        Fn::GetAtt:
        - InfraOperationsChangeAuditLambda
        - Arn
      Protocol: lambda
      TopicArn: !Ref InfraOperationsChangeEventTopic
    Type: AWS::SNS::Subscription
  InfraOperationsChangeAuditLambdaInvokePermission: 
    Type: 'AWS::Lambda::Permission'
    Properties: 
      Action: 'lambda:InvokeFunction'
      Principal: 'sns.amazonaws.com'
      SourceArn: !Ref InfraOperationsChangeEventTopic
      FunctionName: 
        Fn::GetAtt:
        - InfraOperationsChangeAuditLambda
        - Arn
